#!/bin/sh

if [[ $(uname -p) == 'arm' ]]; then
echo "Firmware password not supported by this architecture. Exiting."
exit 0
fi

checkFirmwarePassword=$( /usr/sbin/firmwarepasswd -check )

if [ $(uname -p) == "i386" ] && [ "$checkFirmwarePassword" == "Password Enabled: Yes" ]; then
echo "Intel processor installed and firmware password already set. Exiting."
exit 0 
fi

if [ $(uname -p) == "i386" ] && [ "$checkFirmwarePassword" == "Password Enabled: No" ]; then
echo "Intel processor installed and firmware password not set. Running firmware password installation policy."
jamf policy -trigger setfirmware
exit 0
else
exit 0 
fi
